version: '3.9'

services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/nginx.docker
    container_name: nginx
    volumes:
      - ./:/var/www:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    ports:
      - "8080:443"

  app:
    build:
      context: ./
      dockerfile: docker/php-fpm/php-fpm.docker
      args:
        - USER_ID
        - GROUP_ID
    container_name: app
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ELASTICSEARCH_HOSTS: elasticsearch:9200
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
      - redis
      - elasticsearch

  php-cli:
    build:
      context: ./
      dockerfile: docker/php-cli/php-cli.docker
      args:
        - USER_ID
        - GROUP_ID
    container_name: php-cli
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ELASTICSEARCH_HOSTS: elasticsearch:9200
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
      - redis
      - elasticsearch

  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 33061:3306

  redis:
    image: redis:6.2.1-alpine
    container_name: redis
    ports:
      - "63791:6379"

  node:
    user: ${USER_ID}:${GROUP_ID}
    image: node:15.12.0-alpine3.10
    container_name: node
    volumes:
      - ./:/var/www
    working_dir: /var/www

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: es
    environment:
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./storage/docker/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
